/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Exercise`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Macro`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Meal`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/MuscleGroup`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/NutritionPlan`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/User`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/WorkoutPlan`; params?: Router.UnknownInputParams; } | { pathname: `/Components/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/AppNavbar/AppNavbar`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/AuthenticationStyle`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/FillUserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Nutrition/NutritionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Workout/WorkoutScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/App`; params?: Router.UnknownOutputParams; } | { pathname: `/types`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/Exercise`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/Macro`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/Meal`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/MuscleGroup`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/NutritionPlan`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/User`; params?: Router.UnknownOutputParams; } | { pathname: `/Classes/WorkoutPlan`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/AppNavbar/AppNavbar`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Authentication/AuthenticationStyle`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Authentication/FillUserProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Authentication/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Authentication/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Nutrition/NutritionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Components/Workout/WorkoutScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/App${`?${string}` | `#${string}` | ''}` | `/types${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/Classes/Exercise${`?${string}` | `#${string}` | ''}` | `/Classes/Macro${`?${string}` | `#${string}` | ''}` | `/Classes/Meal${`?${string}` | `#${string}` | ''}` | `/Classes/MuscleGroup${`?${string}` | `#${string}` | ''}` | `/Classes/NutritionPlan${`?${string}` | `#${string}` | ''}` | `/Classes/User${`?${string}` | `#${string}` | ''}` | `/Classes/WorkoutPlan${`?${string}` | `#${string}` | ''}` | `/Components/HomeScreen${`?${string}` | `#${string}` | ''}` | `/Components/AppNavbar/AppNavbar${`?${string}` | `#${string}` | ''}` | `/Components/Authentication/AuthenticationStyle${`?${string}` | `#${string}` | ''}` | `/Components/Authentication/FillUserProfile${`?${string}` | `#${string}` | ''}` | `/Components/Authentication/LoginScreen${`?${string}` | `#${string}` | ''}` | `/Components/Authentication/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/Components/Nutrition/NutritionScreen${`?${string}` | `#${string}` | ''}` | `/Components/Workout/WorkoutScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/App`; params?: Router.UnknownInputParams; } | { pathname: `/types`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Exercise`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Macro`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/Meal`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/MuscleGroup`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/NutritionPlan`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/User`; params?: Router.UnknownInputParams; } | { pathname: `/Classes/WorkoutPlan`; params?: Router.UnknownInputParams; } | { pathname: `/Components/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/AppNavbar/AppNavbar`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/AuthenticationStyle`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/FillUserProfile`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Authentication/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Nutrition/NutritionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Components/Workout/WorkoutScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
